/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActivityTripResponse { 
    id?: string;
    startedAt?: string;
    endedAt?: string;
    distanceKm?: number;
    durationMinutes?: number;
    idleMinutes?: number;
    maxSpeedKmh?: number;
}

