/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityInProgressTripResponse } from './activityInProgressTripResponse';
import { DailyDistancePointResponse } from './dailyDistancePointResponse';
import { ActivityTripResponse } from './activityTripResponse';
import { ActivityReportSummaryResponse } from './activityReportSummaryResponse';


export interface ActivityReportResponse { 
    vehicleId?: string;
    summary?: ActivityReportSummaryResponse;
    dailyDistances?: Array<DailyDistancePointResponse>;
    trips?: Array<ActivityTripResponse>;
    inProgressTrip?: ActivityInProgressTripResponse;
}

