/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AlertResponse { 
    id?: string;
    vehicleId?: string;
    vehicleLabel?: string;
    alertType?: string;
    context?: string;
    contextLabel?: string;
    occurredAt?: string;
    acknowledged?: boolean;
    acknowledgedAt?: string;
    acknowledgedBy?: string;
}

