/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DispatcherSelfView { 
    id?: string;
    organizationId?: string;
    email?: string;
    role?: DispatcherSelfView.RoleEnum;
}
export namespace DispatcherSelfView {
    export const RoleEnum = {
        Dispatcher: 'DISPATCHER',
        FleetAdmin: 'FLEET_ADMIN',
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


