/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleStateResponse } from './vehicleStateResponse';


export interface FleetStateResponse { 
    vehicles?: Array<VehicleStateResponse>;
}

