/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoPointResponse } from './geoPointResponse';


export interface GeofenceResponse { 
    id?: string;
    name?: string;
    rule?: GeofenceResponse.RuleEnum;
    dwellSecs?: number;
    vertices?: Array<GeoPointResponse>;
    createdAt?: string;
}
export namespace GeofenceResponse {
    export const RuleEnum = {
        OnEnter: 'ON_ENTER',
        OnExit: 'ON_EXIT',
        OnDwell: 'ON_DWELL',
    } as const;
    export type RuleEnum = typeof RuleEnum[keyof typeof RuleEnum];
}


