/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoPointRequest } from './geoPointRequest';


export interface GeofenceRequest { 
    name: string;
    rule: GeofenceRequest.RuleEnum;
    dwellSecs?: number;
    shape: GeofenceRequest.ShapeEnum;
    vertices?: Array<GeoPointRequest>;
    center?: GeoPointRequest;
    radiusMeters?: number;
}
export namespace GeofenceRequest {
    export const RuleEnum = {
        OnEnter: 'ON_ENTER',
        OnExit: 'ON_EXIT',
        OnDwell: 'ON_DWELL',
    } as const;
    export type RuleEnum = typeof RuleEnum[keyof typeof RuleEnum];
    export const ShapeEnum = {
        Polygon: 'POLYGON',
        Circle: 'CIRCLE',
    } as const;
    export type ShapeEnum = typeof ShapeEnum[keyof typeof ShapeEnum];
}


