/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MqttCredentialsResponse { 
    username?: string;
    password?: string;
    wsUrl?: string;
    expiresAt?: string;
}

