/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehicleStateResponse { 
    vehicleId?: string;
    label?: string;
    lat?: number;
    lon?: number;
    recordedAt?: string;
    motionState?: VehicleStateResponse.MotionStateEnum;
    online?: boolean;
}
export namespace VehicleStateResponse {
    export const MotionStateEnum = {
        Moving: 'MOVING',
        Idling: 'IDLING',
        Stopped: 'STOPPED',
    } as const;
    export type MotionStateEnum = typeof MotionStateEnum[keyof typeof MotionStateEnum];
}


