spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetpulse
    username: fleetpulse
    password: fleetpulse

fleetpulse:
  mqtt:
    broker-url: tcp://localhost:1883
    service:
      username: internal-services
      password: fleetpulse-dynsec-service
