/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActivityReportResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ActivityReportControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/vehicles/{vehicleId}/activity-report
     * @param vehicleId 
     * @param from 
     * @param to 
     */
    report(vehicleId: string, from: string, to: string, extraHttpRequestParams?: any): Observable<ActivityReportResponse>;

}
