/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AlertResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AlertsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/alerts/{id}/acknowledge
     * @param id 
     */
    acknowledge(id: string, extraHttpRequestParams?: any): Observable<AlertResponse>;

    /**
     * 
     * 
     * @endpoint get /api/alerts
     * @param type 
     * @param vehicleId 
     * @param acknowledged 
     * @param from 
     * @param to 
     */
    list1(type?: Array<string>, vehicleId?: string, acknowledged?: boolean, from?: string, to?: string, extraHttpRequestParams?: any): Observable<Array<AlertResponse>>;

}
