export * from './activityReportController.service';
import { ActivityReportControllerService } from './activityReportController.service';
export * from './activityReportController.serviceInterface';
export * from './alertsController.service';
import { AlertsControllerService } from './alertsController.service';
export * from './alertsController.serviceInterface';
export * from './csrfTokenController.service';
import { CsrfTokenControllerService } from './csrfTokenController.service';
export * from './csrfTokenController.serviceInterface';
export * from './deviceCredentialController.service';
import { DeviceCredentialControllerService } from './deviceCredentialController.service';
export * from './deviceCredentialController.serviceInterface';
export * from './dispatcherSessionController.service';
import { DispatcherSessionControllerService } from './dispatcherSessionController.service';
export * from './dispatcherSessionController.serviceInterface';
export * from './fleetStateController.service';
import { FleetStateControllerService } from './fleetStateController.service';
export * from './fleetStateController.serviceInterface';
export * from './geofenceController.service';
import { GeofenceControllerService } from './geofenceController.service';
export * from './geofenceController.serviceInterface';
export * from './mqttCredentialsController.service';
import { MqttCredentialsControllerService } from './mqttCredentialsController.service';
export * from './mqttCredentialsController.serviceInterface';
export * from './vehicleDestinationController.service';
import { VehicleDestinationControllerService } from './vehicleDestinationController.service';
export * from './vehicleDestinationController.serviceInterface';
export * from './vehicleTrackController.service';
import { VehicleTrackControllerService } from './vehicleTrackController.service';
export * from './vehicleTrackController.serviceInterface';
export const APIS = [ActivityReportControllerService, AlertsControllerService, CsrfTokenControllerService, DeviceCredentialControllerService, DispatcherSessionControllerService, FleetStateControllerService, GeofenceControllerService, MqttCredentialsControllerService, VehicleDestinationControllerService, VehicleTrackControllerService];
