/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DeviceCredentialResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DeviceCredentialControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/devices/{deviceId}/mqtt-credentials
     * @param deviceId 
     */
    provision(deviceId: string, extraHttpRequestParams?: any): Observable<DeviceCredentialResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/devices/{deviceId}/mqtt-credentials
     * @param deviceId 
     */
    revoke(deviceId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/devices/{deviceId}/mqtt-credentials/rotate
     * @param deviceId 
     */
    rotate(deviceId: string, extraHttpRequestParams?: any): Observable<DeviceCredentialResponse>;

}
