/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DispatcherSelfView } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DispatcherSessionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/dispatchers/{id}
     * @param id 
     */
    findDispatcher(id: string, extraHttpRequestParams?: any): Observable<DispatcherSelfView>;

    /**
     * 
     * 
     * @endpoint get /api/dispatchers/me
     */
    me(extraHttpRequestParams?: any): Observable<DispatcherSelfView>;

}
