/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GeofenceRequest } from '../model/models';
import { GeofenceResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GeofenceControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/geofences/{id}
     * @param id 
     */
    _delete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/geofences
     * @param geofenceRequest 
     */
    create(geofenceRequest: GeofenceRequest, extraHttpRequestParams?: any): Observable<GeofenceResponse>;

    /**
     * 
     * 
     * @endpoint get /api/geofences/{id}
     * @param id 
     */
    get(id: string, extraHttpRequestParams?: any): Observable<GeofenceResponse>;

    /**
     * 
     * 
     * @endpoint get /api/geofences
     */
    list(extraHttpRequestParams?: any): Observable<Array<GeofenceResponse>>;

    /**
     * 
     * 
     * @endpoint put /api/geofences/{id}
     * @param id 
     * @param geofenceRequest 
     */
    update(id: string, geofenceRequest: GeofenceRequest, extraHttpRequestParams?: any): Observable<GeofenceResponse>;

}
