/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GeoPointRequest } from '../model/models';
import { VehicleDestinationResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VehicleDestinationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint put /api/vehicles/{vehicleId}/destination
     * @param vehicleId 
     * @param geoPointRequest 
     */
    assign(vehicleId: string, geoPointRequest: GeoPointRequest, extraHttpRequestParams?: any): Observable<VehicleDestinationResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/vehicles/{vehicleId}/destination
     * @param vehicleId 
     */
    clear(vehicleId: string, extraHttpRequestParams?: any): Observable<{}>;

}
