/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TrackPointResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VehicleTrackControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/vehicles/{vehicleId}/track
     * @param vehicleId 
     * @param from 
     * @param to 
     */
    track(vehicleId: string, from?: string, to?: string, extraHttpRequestParams?: any): Observable<Array<TrackPointResponse>>;

}
